### ISSUE TITLE
I don't understand how to import gridle into my project

### ISSUE THREAD

**Issue by elron** [Coffeekraken/gridle#133]
Hey,
Sorry for the newbie questions, I'm still learning NPM ^_^"

I don't really understand how to add gridle to my project... how does it work?
should the gridle folder & files move inside my project, or stay in node_module folder?
Is there a quick command to do that?

In [quick start](https://www.npmjs.com/package/gridle#quick-start) it says to `import "gridle/gridle"`, which sounds obvious, but I don't understand where or how.

Help! 😮

**Comment by elron** [comment]
Ok I figured [here](https://github.com/Coffeekraken/gridle#install) that I needed to use `import 'node_modules/coffeekraken-gridle/index'` instead, and it worked!
YAY.

The only thing left to do is fix the importing code [quick start](https://www.npmjs.com/package/gridle#quick-start) "Importing gridle" part to the above.

**Comment by olivierbossel** [comment]
Hi man,
Thanks for the feedback.
The issue is that you've just mixed two of the gridle version.
The one called "gridle" is the old one that is still at version 2.x. It has been moved to the coffeekraken organisation here and you just have to follow the instructions in this repo.

- Old NPM package page : https://www.npmjs.com/package/gridle
- New NPM package page : https://www.npmjs.com/package/coffeekraken-gridle

For the "@", you're right. It's just missing. I will make a fix :)
