### ISSUE TITLE
Compliance with dart sass?

### ISSUE THREAD

**Issue by Neograph734** [Coffeekraken/gridle#145]
I just reinstalled my computer, and upon installing Sass, I learned that ruby Sass is discontinued (bugfixes till march 26th 2019) and that it is replaced by dart Sass. 

This however does not seem to be compatible with gridle:

```
cmd.exe /D /C call C:\dart-sass\sass.bat style.scss:..\stylesheets\style.css
DEPRECATION WARNING on line 82, column 4 of gridle\_api.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
	} @elseif type-of($states) == list
	  ^^^^^^^

DEPRECATION WARNING on line 97, column 4 of gridle\_api.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
	} @elseif type-of($states) == map {
	  ^^^^^^^

DEPRECATION WARNING on line 414, column 6 of gridle\_generate-mixins.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
			} @elseif type-of($value) == bool {
			  ^^^^^^^

DEPRECATION WARNING on line 416, column 6 of gridle\_generate-mixins.scss: 
@elseif is deprecated and will not be supported in future Sass versions.
Use "@else if" instead.
			} @elseif type-of($value) == map {
			  ^^^^^^^

Error: From line 42, column 3 of gridle\_mixins.scss: 
		%#{$stateName}-#{$for} {
		^^^^^^^^^^^^^^^^^^^^^^^
You may not @extend selectors across media queries.
			@extend %#{$_g-current-stateName}-#{$package} !optional;
			^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  gridle\_mixins.scss 306:4  root stylesheet

Process finished with exit code 65

```

It was a new thing for me, so I was wondering if you were aware of this change in Sass, and if there are any plans to update Gridle to be compatible with dart Sass?

**Comment by olivierbossel** [comment]
Hi there,
First thanks for your interest in gridle and thanks for your feedback.
I'm not aware of dart sass so I cannot tells you more on that for now. I have to make tests etc...
I can encourage you to use node-sass as a replacement cause It works very well and is very performant.
I will investigate on dart sass but I can't promise you that I will make big changes to gridle for that. Will see

**Comment by Neograph734** [comment]
Hi Olivier,

So far ruby sass has been working pretty well for me. Dart-sass was new to me as well, but appears to be the go-to direction. The sass site links to it as standalone installation, and npm and chocolatery installation methods also appear to be pulling from some dart image. 
My issues above were specifically with the standalone installation for Windows, but it could be that these other installation methods have the same effect. 

You can read about it on the sass blog: http://sass.logdown.com/posts/7081811

In the meantime I will see if I can get node-sass up and running (thanks for the suggestion :) ).

**Comment by Windvis** [comment]
Since dart-sass is the new reference implementation, griddle should be made compatible with it, in my opinion. We use griddle in some of our projects, and we can't modernise our build tooling because of this problem.

Maybe you can add a warning in the readme about the dart-sass incompatibility for now?

**Comment by olivierbossel** [comment]
The issue here is that Gridle make heavy use on silent classes that are scoped (initialized) inside a media query and dart sass seems to doesn't care about that and set these silent classes in the root scope. Then when I try to extend one of these silent classes from inside a media query, the error listed above pops up. As this is a core principle of Gridlev3, it will be difficult to rearrange the code to make it work with these sass implementations.
By the way, I will release Gridle v4 (in release candidate for now) soon. It will be a little bit different and a lot simpler so I hope this will be a kind of answer to your issues

**Comment by rastapopougros** [comment]
Hello, just to add a bit more information and a little question : now in 2022, "node-sass" is explicitly marked as deprecated, so the compiler to use is de facto "sass" (means dart sass) who is the one following the standard (for ex math.div instead of "/" as described https://sass-lang.com/documentation/breaking-changes/slash-div). Many frameworks already changed and only work with "sass" and never with "node-sass". So this is not an option at all.

As a consequence, I understand that the only solution is to use Gridle 4 ? (which compiles ok with "sass" ?)

But what if we have production code with Gridle 3, and absolutely can't change all the architecture to use Gridle 4 and just updated npm/gulp stack and… all broken 'cause new versions can't compile Gridle 3 ? :(

I will try to downgrade all versions of the stack gulp etc, until all compile again…
